name: "ce-boostup-xii"

services:
  api:
    build: api
    container_name: ce-boostup-xii-api
    ports:
      - "3000:3000"
    volumes:
      - ./api/attachments:/app/attachments
      - ./api/avatars:/app/avatars
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - MARIADB_HOST=mariadb
      - COMPILER_API_URL=http://compiler:3001
    healthcheck:
      test: "curl -I http://localhost:3000 || exit 1"
      start_period: 10s
      start_interval: 1s
    restart: unless-stopped

  compiler:
    build: compiler
    container_name: ce-boostup-xii-compiler
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    security_opt:
      - apparmor:unconfined
    expose:
      - "3001"
    tmpfs:
      - /run/isolate:exec,mode=755,size=1048576,uid=0,gid=0
      - /var/local/lib/isolate:exec,mode=755,size=4294967296,uid=0,gid=0
      - /tmp/ce-boostup-xii:mode=755,size=1073741824,uid=1000,gid=1000
    deploy:
      resources:
        limits:
          memory: 4GB
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3001 || exit 1"
      start_period: 10s
      start_interval: 1s
    restart: unless-stopped

  mariadb:
    image: mariadb:11
    container_name: ce-boostup-xii-mariadb
    volumes:
      - ./api/mariadb-data:/var/lib/mysql
      - ./api/mariadb.cnf:/etc/mysql/conf.d/mariadb.cnf
    expose:
      - "3306"
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=${MARIADB_DATABASE:-ceboostupxii}
      - MARIADB_USER=${MARIADB_USER:-ceboostupxii}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD:-ceboostupxii}
    healthcheck:
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su=mysql",
          "--connect",
          "--innodb_initialized",
        ]
      start_period: 10s
      start_interval: 1s
    restart: unless-stopped
